-- Autonomous Agent System
-- ========================
-- Tables for AI agent orchestration, task tracking, content queue, and outreach pipeline.

-- Agent run history (each time an agent executes)
CREATE TABLE IF NOT EXISTS agent_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_name TEXT NOT NULL,           -- 'content', 'social', 'outreach', 'sales', 'data', 'support', 'orchestrator'
  status TEXT NOT NULL DEFAULT 'running',  -- 'running', 'completed', 'failed', 'skipped'
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  duration_ms INTEGER,
  tasks_completed INTEGER DEFAULT 0,
  tasks_failed INTEGER DEFAULT 0,
  error_message TEXT,
  metadata JSONB DEFAULT '{}',        -- agent-specific output data
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_agent_runs_name ON agent_runs(agent_name);
CREATE INDEX idx_agent_runs_started ON agent_runs(started_at DESC);

-- Content queue (generated by Content Agent, consumed by Social Agent)
CREATE TABLE IF NOT EXISTS content_queue (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  content_type TEXT NOT NULL,         -- 'before_after', 'caption', 'blog_post', 'video_script', 'reel'
  platform TEXT,                      -- 'instagram', 'tiktok', 'facebook', 'linkedin', 'twitter', 'blog'
  title TEXT,
  body TEXT NOT NULL,
  media_urls TEXT[] DEFAULT '{}',     -- Array of image/video URLs
  hashtags TEXT[] DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'queued',  -- 'queued', 'scheduled', 'posted', 'failed'
  scheduled_for TIMESTAMPTZ,
  posted_at TIMESTAMPTZ,
  post_url TEXT,                      -- URL of the published post
  engagement JSONB DEFAULT '{}',      -- { likes, comments, shares, impressions }
  agent_run_id UUID REFERENCES agent_runs(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_content_queue_status ON content_queue(status);
CREATE INDEX idx_content_queue_platform ON content_queue(platform);
CREATE INDEX idx_content_queue_scheduled ON content_queue(scheduled_for) WHERE status = 'queued';

-- Outreach pipeline (managed by Outreach Agent)
CREATE TABLE IF NOT EXISTS outreach_leads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  company TEXT,
  role TEXT,                          -- 'photographer', 'agent', 'broker'
  city TEXT,
  state TEXT,
  source TEXT,                        -- 'google_maps', 'realtor_com', 'manual', 'referral'
  website TEXT,
  phone TEXT,
  status TEXT NOT NULL DEFAULT 'new', -- 'new', 'emailed', 'followed_up', 'responded', 'converted', 'unsubscribed', 'bounced'
  email_sent_at TIMESTAMPTZ,
  followup_1_at TIMESTAMPTZ,
  followup_2_at TIMESTAMPTZ,
  responded_at TIMESTAMPTZ,
  converted_at TIMESTAMPTZ,          -- When they signed up on SnapR
  snapr_user_id UUID,                -- Links to profiles.id if they convert
  notes TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_outreach_leads_email ON outreach_leads(email);
CREATE INDEX idx_outreach_leads_status ON outreach_leads(status);
CREATE INDEX idx_outreach_leads_city ON outreach_leads(city, state);

-- Outreach email log (every email sent by the agent)
CREATE TABLE IF NOT EXISTS outreach_emails (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id UUID NOT NULL REFERENCES outreach_leads(id) ON DELETE CASCADE,
  email_type TEXT NOT NULL,           -- 'initial', 'followup_1', 'followup_2', 'custom'
  subject TEXT NOT NULL,
  body TEXT NOT NULL,
  resend_id TEXT,                     -- Resend message ID for tracking
  status TEXT NOT NULL DEFAULT 'sent', -- 'sent', 'delivered', 'opened', 'clicked', 'bounced', 'failed'
  opened_at TIMESTAMPTZ,
  clicked_at TIMESTAMPTZ,
  agent_run_id UUID REFERENCES agent_runs(id),
  sent_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_outreach_emails_lead ON outreach_emails(lead_id);

-- Agent configuration (tunable parameters per agent)
CREATE TABLE IF NOT EXISTS agent_config (
  agent_name TEXT PRIMARY KEY,
  enabled BOOLEAN NOT NULL DEFAULT true,
  schedule TEXT,                       -- cron expression or 'manual'
  config JSONB NOT NULL DEFAULT '{}',  -- agent-specific config
  last_run_at TIMESTAMPTZ,
  last_status TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Seed default agent configs
INSERT INTO agent_config (agent_name, enabled, schedule, config) VALUES
  ('orchestrator', true, '0 8 * * *', '{"timezone": "America/New_York"}'),
  ('content', true, '0 7 * * *', '{"daily_before_afters": 3, "daily_captions": 5, "weekly_blog_posts": 1}'),
  ('social', true, '0 9,13,17 * * *', '{"platforms": ["instagram", "tiktok", "facebook", "linkedin", "twitter"], "posts_per_run": 2}'),
  ('outreach', true, '0 10 * * 1-5', '{"daily_new_leads": 20, "daily_emails": 50, "target_cities": ["Los Angeles", "New York", "Miami", "Chicago", "Houston", "Dallas", "Phoenix", "San Francisco", "Seattle", "Atlanta"]}'),
  ('sales', true, '0 18 * * *', '{"free_trial_reminder_days": [3, 7, 10], "inactive_days_trigger": 7, "discount_percent": 20}'),
  ('data', true, '0 23 * * *', '{"track_ga4": true, "track_stripe": true, "track_social": true, "cpa_pause_threshold": 50}'),
  ('support', true, 'realtime', '{"auto_reply": true, "escalation_email": "support@snap-r.com", "max_context_messages": 10}')
ON CONFLICT (agent_name) DO NOTHING;

-- Daily metrics (aggregated by Data Agent)
CREATE TABLE IF NOT EXISTS agent_daily_metrics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  -- Traffic
  website_visitors INTEGER DEFAULT 0,
  signups INTEGER DEFAULT 0,
  signup_conversion_rate NUMERIC(5,2) DEFAULT 0,
  -- Revenue
  mrr_cents INTEGER DEFAULT 0,
  new_subscribers INTEGER DEFAULT 0,
  churned_subscribers INTEGER DEFAULT 0,
  revenue_today_cents INTEGER DEFAULT 0,
  -- Social
  total_followers JSONB DEFAULT '{}',  -- { instagram: X, tiktok: X, ... }
  posts_published INTEGER DEFAULT 0,
  total_engagement INTEGER DEFAULT 0,
  top_post_url TEXT,
  -- Outreach
  emails_sent INTEGER DEFAULT 0,
  emails_opened INTEGER DEFAULT 0,
  email_open_rate NUMERIC(5,2) DEFAULT 0,
  leads_found INTEGER DEFAULT 0,
  leads_converted INTEGER DEFAULT 0,
  -- Ads
  ad_spend_cents INTEGER DEFAULT 0,
  ad_clicks INTEGER DEFAULT 0,
  ad_conversions INTEGER DEFAULT 0,
  cost_per_acquisition_cents INTEGER DEFAULT 0,
  -- System
  errors_count INTEGER DEFAULT 0,
  uptime_percent NUMERIC(5,2) DEFAULT 100,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_agent_daily_metrics_date ON agent_daily_metrics(date);

-- RLS: Service role only (agents run server-side)
ALTER TABLE agent_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE content_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE outreach_leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE outreach_emails ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_daily_metrics ENABLE ROW LEVEL SECURITY;

-- Service role bypass for all agent tables
CREATE POLICY "Service role full access" ON agent_runs FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role full access" ON content_queue FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role full access" ON outreach_leads FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role full access" ON outreach_emails FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role full access" ON agent_config FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role full access" ON agent_daily_metrics FOR ALL USING (auth.role() = 'service_role');
